spring.application.name=shotlog

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/shotlogdb
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements
spring.jpa.show-sql=true
